"use client";

import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, CalendarClock, CheckCircle2, Download, Mail, Plus, RefreshCw, Trash2, XCircle } from "lucide-react";

type Client = { id: string; name: string; source: string; externalAccountId?: string | null; connectionRef?: string | null; enabled: boolean };
type RunItem = { id: string; clientName: string; source: string; status: string; invoiceCount: number; amountCents: number; error?: string | null };
type Run = { id: string; periodKey: string; status: string; createdAt: string; emailedAt?: string | null; items: RunItem[] };
type Data = { clients: Client[]; schedule: { enabled: boolean; dayOfMonth: number; time: string; timezone: string; recipients: string[] }; runs: Run[]; sources: string[]; integrations: { googleAds: { accountEmail: string; label?: string | null }[]; metaConnectionCount: number; billingMailboxConnected: boolean } };
const sourceLabels: Record<string, string> = { HOLDED: "Holded", META: "Meta", GOOGLE_ADS: "Google Ads", BANK: "Banco" };
const badge = (status: string) => status === "DOWNLOADED" ? "bg-emerald-100 text-emerald-800" : status === "FAILED" ? "bg-red-600 text-white ring-4 ring-red-100" : status === "RUNNING" ? "bg-blue-100 text-blue-800" : "bg-amber-100 text-amber-900";

export default function AccountancyInvoicesClient() {
  const [data, setData] = useState<Data | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [form, setForm] = useState({ name: "", source: "META", externalAccountId: "", connectionRef: "" });
  const [recipients, setRecipients] = useState("info@negociovivo.com");
  const load = async () => { const res = await fetch("/api/accountancy-invoices", { cache: "no-store" }); const json = await res.json(); if (!res.ok) throw new Error(json.error); setData(json); setRecipients((json.schedule.recipients || []).join(", ")); };
  useEffect(() => { load().catch((e) => setError(e.message)); }, []);
  const latest = data?.runs[0];
  const failed = useMemo(() => latest?.items.filter((item) => item.status === "FAILED") ?? [], [latest]);
  async function request(url: string, method: string, body?: unknown) { setBusy(true); setError(""); try { const res = await fetch(url, { method, headers: { "Content-Type": "application/json" }, body: body ? JSON.stringify(body) : undefined }); const json = await res.json(); if (!res.ok) throw new Error(json.error); await load(); return json; } catch (e: any) { setError(e.message || "Error inesperado"); } finally { setBusy(false); } }
  if (!data) return <div className="rounded-xl border bg-white p-8 text-slate-500">Cargando control de facturas…</div>;
  return <div className="space-y-6">
    <nav className="flex gap-2 border-b border-slate-200"><a href="/facturacion" className="px-4 py-3 text-sm font-semibold text-slate-500">Facturación</a><span className="border-b-2 border-brand-600 px-4 py-3 text-sm font-bold text-brand-700">Facturas gestoría</span></nav>
    {error && <div className="rounded-xl border-2 border-red-300 bg-red-50 p-4 font-semibold text-red-800"><AlertTriangle className="mr-2 inline h-5 w-5" />{error}</div>}
    <section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-lg font-bold">Conexiones permanentes</h2><p className="mt-1 text-sm text-slate-500">Autorización única; las descargas mensuales posteriores se ejecutan en el servidor sin pestañas abiertas.</p><div className="mt-4 grid gap-3 md:grid-cols-3">{[{ email: "tunegociovivo@gmail.com", label: "Google Ads · Negocio Vivo" }, { email: "eroskifranquicias.marketing@gmail.com", label: "Google Ads · Eroski" }].map((account) => { const connected = data.integrations.googleAds.some((row) => row.accountEmail === account.email); return <div key={account.email} className={`rounded-xl border-2 p-4 ${connected ? "border-emerald-300 bg-emerald-50" : "border-amber-300 bg-amber-50"}`}><div className="font-bold">{account.label}</div><div className="text-xs text-slate-600">{account.email}</div><div className="mt-3 flex items-center justify-between"><span className={`text-sm font-black ${connected ? "text-emerald-700" : "text-amber-800"}`}>{connected ? "✓ Conectada" : "Pendiente de conectar"}</span><a href={`/api/integrations/google-ads/connect?account=${encodeURIComponent(account.email)}`} className="rounded-lg bg-slate-900 px-3 py-2 text-sm font-bold text-white">{connected ? "Renovar" : "Conectar"}</a></div></div>; })}<div className={`rounded-xl border-2 p-4 ${data.integrations.billingMailboxConnected ? "border-emerald-300 bg-emerald-50" : "border-red-300 bg-red-50"}`}><div className="font-bold">Meta · Recibos por correo</div><div className="text-xs text-slate-600">Clasificación por ID de cuenta y periodo</div><div className={`mt-3 text-sm font-black ${data.integrations.billingMailboxConnected ? "text-emerald-700" : "text-red-700"}`}>{data.integrations.billingMailboxConnected ? "✓ Buzón conectado" : "¡Buzón no configurado!"}</div></div></div></section>
    {failed.length > 0 && <section className="rounded-2xl border-4 border-red-500 bg-red-50 p-5 shadow-lg"><h2 className="flex items-center gap-2 text-xl font-black text-red-800"><XCircle /> {failed.length} cuentas con facturas no descargadas</h2><div className="mt-3 grid gap-2 md:grid-cols-2">{failed.map((item) => <div key={item.id} className="rounded-lg bg-white p-3 font-semibold text-red-900">{item.clientName} · {sourceLabels[item.source] || item.source}<div className="text-sm font-normal">{item.error || "No se pudo completar la descarga"}</div></div>)}</div></section>}
    <div className="grid gap-4 lg:grid-cols-3">
      <section className="rounded-2xl border bg-white p-5 shadow-sm lg:col-span-2"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-bold text-slate-900">Ejecución mensual</h2><p className="text-sm text-slate-500">Descarga siempre el mes natural anterior.</p></div><button disabled={busy} onClick={() => request("/api/accountancy-invoices", "POST", { action: "run" })} className="inline-flex items-center gap-2 rounded-xl bg-brand-600 px-4 py-3 font-bold text-white hover:bg-brand-700 disabled:opacity-50"><Download className="h-5 w-5" /> Descargar ahora</button></div>
        <div className="mt-5 grid gap-3 sm:grid-cols-3"><label className="text-sm font-semibold text-slate-700">Día del mes<input type="number" min={1} max={28} value={data.schedule.dayOfMonth} onChange={(e) => setData({ ...data, schedule: { ...data.schedule, dayOfMonth: Number(e.target.value) } })} className="mt-1 w-full rounded-lg border p-2" /></label><label className="text-sm font-semibold text-slate-700">Hora<input type="time" value={data.schedule.time} onChange={(e) => setData({ ...data, schedule: { ...data.schedule, time: e.target.value } })} className="mt-1 w-full rounded-lg border p-2" /></label><label className="flex items-end gap-2 rounded-lg bg-slate-50 p-3 font-semibold"><input type="checkbox" checked={data.schedule.enabled} onChange={(e) => setData({ ...data, schedule: { ...data.schedule, enabled: e.target.checked } })} /> Programación activa</label></div>
        <button disabled={busy} onClick={() => request("/api/accountancy-invoices", "PATCH", { action: "schedule", ...data.schedule, recipients })} className="mt-4 inline-flex items-center gap-2 rounded-lg border border-brand-300 px-4 py-2 font-semibold text-brand-700"><CalendarClock className="h-4 w-4" /> Guardar programación</button>
      </section>
      <section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="flex items-center gap-2 text-lg font-bold"><Mail className="h-5 w-5" /> Enviar a gestoría</h2><label className="mt-3 block text-sm font-semibold">Destinatarios<input value={recipients} onChange={(e) => setRecipients(e.target.value)} className="mt-1 w-full rounded-lg border p-2" placeholder="correo1@..., correo2@..." /></label><button disabled={!latest || busy} onClick={() => { if (confirm(`Se enviarán las facturas de ${latest?.periodKey} a ${recipients}. ¿Continuar?`)) request("/api/accountancy-invoices/send", "POST", { runId: latest?.id, recipients }); }} className="mt-4 w-full rounded-xl bg-slate-900 px-4 py-3 font-bold text-white disabled:opacity-40">Enviar última ejecución</button>{latest?.emailedAt && <p className="mt-2 text-xs text-emerald-700">Enviado el {new Date(latest.emailedAt).toLocaleString("es-ES")}</p>}</section>
    </div>
    <section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-lg font-bold">Añadir cliente o cuenta</h2><div className="mt-3 grid gap-3 md:grid-cols-[1fr_180px_1fr_1fr_auto]"><input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className="rounded-lg border p-2" placeholder="Nombre del cliente" /><select value={form.source} onChange={(e) => setForm({ ...form, source: e.target.value, connectionRef: "" })} className="rounded-lg border p-2">{data.sources.map((source) => <option key={source} value={source}>{sourceLabels[source] || source}</option>)}</select><input value={form.externalAccountId} onChange={(e) => setForm({ ...form, externalAccountId: e.target.value })} className="rounded-lg border p-2" placeholder="ID de cuenta externo" />{form.source === "GOOGLE_ADS" ? <select value={form.connectionRef} onChange={(e) => setForm({ ...form, connectionRef: e.target.value })} className="rounded-lg border p-2"><option value="">Administrador Google</option><option value="tunegociovivo@gmail.com">Negocio Vivo</option><option value="eroskifranquicias.marketing@gmail.com">Eroski</option></select> : <div className="hidden md:block" />}<button disabled={busy || !form.name.trim()} onClick={async () => { await request("/api/accountancy-invoices", "POST", { action: "client", ...form }); setForm({ name: "", source: "META", externalAccountId: "", connectionRef: "" }); }} className="rounded-lg bg-brand-600 px-4 py-2 font-bold text-white"><Plus className="inline h-4 w-4" /> Añadir</button></div></section>
    <section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="flex items-center justify-between border-b p-5"><h2 className="text-lg font-bold">Clientes y medios</h2><span className="text-sm text-slate-500">{data.clients.filter((client) => client.enabled).length} activos</span></div><div className="divide-y">{data.clients.map((client) => { const item = latest?.items.find((row) => row.clientName === client.name && row.source === client.source); return <div key={client.id} className="grid gap-3 p-4 md:grid-cols-[40px_1fr_150px_170px_50px] md:items-center"><input aria-label={`Activar ${client.name}`} type="checkbox" checked={client.enabled} onChange={(e) => request("/api/accountancy-invoices", "PATCH", { id: client.id, enabled: e.target.checked })} className="h-5 w-5" /><div><div className="font-bold text-slate-900">{client.name}</div><div className="text-xs text-slate-500">{client.externalAccountId || "Sin ID externo"}</div></div><span className="rounded-full bg-slate-100 px-3 py-1 text-center text-xs font-bold">{sourceLabels[client.source] || client.source}</span><span className={`rounded-full px-3 py-2 text-center text-xs font-black ${badge(item?.status || "PENDING")}`}>{item?.status === "DOWNLOADED" ? `✓ ${item.invoiceCount} descargadas` : item?.status === "FAILED" ? "¡NO DESCARGADAS!" : "Pendiente"}</span><button aria-label={`Eliminar ${client.name}`} onClick={() => request(`/api/accountancy-invoices?id=${client.id}`, "DELETE")} className="text-slate-400 hover:text-red-600"><Trash2 className="h-5 w-5" /></button></div>; })}{!data.clients.length && <div className="p-8 text-center text-slate-500">Añade la primera cuenta que quieras controlar.</div>}</div></section>
    {latest && <section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="text-lg font-bold">Última ejecución · {latest.periodKey}</h2><span className={`rounded-full px-4 py-2 text-sm font-black ${latest.status === "SUCCESS" ? "bg-emerald-100 text-emerald-800" : latest.status === "FAILED" ? "bg-red-600 text-white" : "bg-amber-100 text-amber-900"}`}>{latest.status}</span></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-emerald-50 p-4"><CheckCircle2 className="text-emerald-600" /><div className="mt-1 text-2xl font-black">{latest.items.filter((i) => i.status === "DOWNLOADED").length}</div><div className="text-sm">Cuentas correctas</div></div><div className="rounded-xl bg-red-50 p-4"><AlertTriangle className="text-red-600" /><div className="mt-1 text-2xl font-black">{failed.length}</div><div className="text-sm">Con incidencias</div></div><div className="rounded-xl bg-blue-50 p-4"><RefreshCw className="text-blue-600" /><div className="mt-1 text-2xl font-black">{latest.items.reduce((sum, item) => sum + item.invoiceCount, 0)}</div><div className="text-sm">Facturas descargadas</div></div></div></section>}
  </div>;
}
