"use client";
import { useState } from "react";
import { ArrowDown, ArrowUp, Plus, Trash2 } from "lucide-react";

type Step={channel:string;delayHours:number;templateBody?:string;subject?:string;requiresReview?:boolean;stopOnReply?:boolean};
type Campaign={id:string;name:string;status:string;dailyLimit:number;startHour?:number;endHour?:number;activeWeekdays?:number[];steps:Step[]};
const channels=[['linkedin_visit','Visitar LinkedIn'],['linkedin_connect','Conectar LinkedIn'],['linkedin_message','Mensaje LinkedIn'],['email','Email'],['whatsapp','WhatsApp asistido'],['task','Tarea manual']];
const dayLabels=['D','L','M','X','J','V','S'];

export default function ProspectingCampaignEditor({campaign,onClose,onSaved}:{campaign:Campaign;onClose:()=>void;onSaved:()=>Promise<void>}){
 const [name,setName]=useState(campaign.name),[limit,setLimit]=useState(campaign.dailyLimit),[start,setStart]=useState(campaign.startHour??9),[end,setEnd]=useState(campaign.endHour??18);
 const [days,setDays]=useState<number[]>(campaign.activeWeekdays||[1,2,3,4,5]),[steps,setSteps]=useState<Step[]>(campaign.steps.map(s=>({...s}))),[saving,setSaving]=useState(false),[error,setError]=useState('');
 function patchStep(index:number,patch:Partial<Step>){setSteps(value=>value.map((step,i)=>i===index?{...step,...patch}:step))}
 function move(index:number,direction:-1|1){const next=index+direction;if(next<0||next>=steps.length)return;const copy=[...steps];[copy[index],copy[next]]=[copy[next],copy[index]];setSteps(copy)}
 async function save(){setSaving(true);setError('');try{const r=await fetch('/api/v1/leads/prospecting',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:campaign.id,action:'update',name,dailyLimit:limit,startHour:start,endHour:end,activeWeekdays:days,steps:steps.map(s=>({...s,stopOnReply:s.stopOnReply??true,requiresReview:s.channel==='email'?!!s.requiresReview:true}))})});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b?.error?.message||'No se pudo guardar');await onSaved();onClose()}catch(e){setError(e instanceof Error?e.message:'Error interno')}finally{setSaving(false)}}
 return <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/50 p-4"><div className="mx-auto my-6 max-w-3xl rounded-2xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><h2 className="text-xl font-bold">Configurar campaña</h2><p className="text-sm text-slate-500">Pausa la campaña antes de modificar la cadencia.</p></div><button onClick={onClose}>×</button></div>{error&&<div className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</div>}
 <div className="mt-5 grid gap-3 md:grid-cols-3"><label className="text-sm md:col-span-2">Nombre<input value={name} onChange={e=>setName(e.target.value)} className="mt-1 w-full rounded-lg border px-3 py-2"/></label><label className="text-sm">Límite diario<input type="number" min={1} max={500} value={limit} onChange={e=>setLimit(Number(e.target.value))} className="mt-1 w-full rounded-lg border px-3 py-2"/></label><label className="text-sm">Desde<input type="number" min={0} max={23} value={start} onChange={e=>setStart(Number(e.target.value))} className="mt-1 w-full rounded-lg border px-3 py-2"/></label><label className="text-sm">Hasta<input type="number" min={1} max={24} value={end} onChange={e=>setEnd(Number(e.target.value))} className="mt-1 w-full rounded-lg border px-3 py-2"/></label><div><span className="text-sm">Días activos</span><div className="mt-1 flex gap-1">{dayLabels.map((label,day)=><button key={day} onClick={()=>setDays(value=>value.includes(day)?value.filter(x=>x!==day):[...value,day])} className={`h-9 w-9 rounded-lg text-xs font-semibold ${days.includes(day)?'bg-indigo-600 text-white':'border'}`}>{label}</button>)}</div></div></div>
 <div className="mt-6 flex items-center justify-between"><h3 className="font-semibold">Cadencia</h3><button onClick={()=>setSteps(v=>[...v,{channel:'task',delayHours:24,templateBody:'',requiresReview:true,stopOnReply:true}])} className="flex items-center gap-1 rounded-lg border px-3 py-2 text-sm"><Plus className="h-4 w-4"/>Añadir paso</button></div><div className="mt-3 space-y-3">{steps.map((step,index)=><div key={index} className="rounded-xl border bg-slate-50 p-4"><div className="flex flex-wrap items-center gap-2"><b className="mr-auto">Paso {index+1}</b><button onClick={()=>move(index,-1)} disabled={!index}><ArrowUp className="h-4 w-4"/></button><button onClick={()=>move(index,1)} disabled={index===steps.length-1}><ArrowDown className="h-4 w-4"/></button><button onClick={()=>steps.length>1&&setSteps(v=>v.filter((_,i)=>i!==index))} disabled={steps.length===1} className="text-red-600"><Trash2 className="h-4 w-4"/></button></div><div className="mt-3 grid gap-3 md:grid-cols-[1fr,140px]"><label className="text-xs">Canal<select value={step.channel} onChange={e=>patchStep(index,{channel:e.target.value,requiresReview:e.target.value==='email'?step.requiresReview:true})} className="mt-1 w-full rounded-lg border bg-white px-3 py-2 text-sm">{channels.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="text-xs">Espera (horas)<input type="number" min={0} max={2160} value={step.delayHours} onChange={e=>patchStep(index,{delayHours:Number(e.target.value)})} className="mt-1 w-full rounded-lg border px-3 py-2 text-sm"/></label></div>{step.channel==='email'&&<label className="mt-3 block text-xs">Asunto<input value={step.subject||''} onChange={e=>patchStep(index,{subject:e.target.value})} className="mt-1 w-full rounded-lg border px-3 py-2 text-sm"/></label>}<label className="mt-3 block text-xs">Mensaje<textarea rows={3} value={step.templateBody||''} onChange={e=>patchStep(index,{templateBody:e.target.value})} className="mt-1 w-full rounded-lg border p-3 text-sm"/></label>{step.channel==='email'&&<label className="mt-3 flex items-center gap-2 text-sm"><input type="checkbox" checked={!!step.requiresReview} onChange={e=>patchStep(index,{requiresReview:e.target.checked})}/>Revisar manualmente antes de enviar</label>}</div>)}</div>
 <div className="mt-6 flex justify-end gap-2"><button onClick={onClose} className="rounded-xl border px-4 py-2">Cancelar</button><button disabled={saving||!name.trim()||!days.length||end<=start} onClick={()=>void save()} className="rounded-xl bg-indigo-600 px-5 py-2 font-semibold text-white disabled:opacity-50">{saving?'Guardando…':'Guardar cambios'}</button></div></div></div>
}
