"use client";
import { useState } from "react";
import { ArrowDown, ArrowUp, GitBranch, Plus, Trash2 } from "lucide-react";
type Condition={field?:string;operator?:string;value?:string|number;onFalse?:string};
type Step={channel:string;delayHours:number;templateBody?:string;subject?:string;requiresReview?:boolean;stopOnReply?:boolean;personalization?:string;condition?:Condition|null;variants?:Array<{body?:string;subject?:string}>|null};
type Campaign={id:string;name:string;status:string;dailyLimit:number;startHour?:number;endHour?:number;activeWeekdays?:number[];steps:Step[]};
const channels=[['linkedin_visit','Visitar LinkedIn'],['linkedin_connect','Conectar LinkedIn'],['linkedin_message','Mensaje LinkedIn'],['email','Email'],['whatsapp','WhatsApp asistido'],['task','Tarea manual']];
const daysText=['D','L','M','X','J','V','S'];
export default function Editor({campaign,onClose,onSaved}:{campaign:Campaign;onClose:()=>void;onSaved:()=>Promise<void>}){
 const [name,setName]=useState(campaign.name),[limit,setLimit]=useState(campaign.dailyLimit),[start,setStart]=useState(campaign.startHour??9),[end,setEnd]=useState(campaign.endHour??18),[days,setDays]=useState<number[]>(campaign.activeWeekdays||[1,2,3,4,5]),[steps,setSteps]=useState<Step[]>(campaign.steps.map(s=>({...s}))),[saving,setSaving]=useState(false),[error,setError]=useState('');
 const change=(i:number,p:Partial<Step>)=>setSteps(v=>v.map((s,j)=>i===j?{...s,...p}:s));
 const move=(i:number,d:-1|1)=>{const j=i+d;if(j<0||j>=steps.length)return;const v=[...steps];[v[i],v[j]]=[v[j],v[i]];setSteps(v)};
 async function save(){setSaving(true);setError('');try{const normalized=steps.map(s=>({...s,personalization:s.personalization||'template',condition:s.condition?.field?s.condition:null,variants:s.variants?.filter(v=>v.body||v.subject)||null,stopOnReply:s.stopOnReply??true,requiresReview:s.channel==='email'?!!s.requiresReview:true}));const r=await fetch('/api/v1/leads/prospecting',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:campaign.id,action:'update',name,dailyLimit:limit,startHour:start,endHour:end,activeWeekdays:days,steps:normalized})});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b?.error?.message||'No se pudo guardar');await onSaved();onClose()}catch(e){setError(e instanceof Error?e.message:'Error interno')}finally{setSaving(false)}}
 return <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/50 p-4"><div className="mx-auto my-6 max-w-4xl rounded-2xl bg-white p-6"><div className="flex justify-between"><div><h2 className="text-xl font-bold">Constructor visual</h2><p className="text-sm text-slate-500">Secuencias condicionales, variantes y personalización profunda.</p></div><button onClick={onClose}>×</button></div>{error&&<div className="mt-3 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</div>}
 <div className="mt-5 grid gap-3 md:grid-cols-3"><label className="text-sm md:col-span-2">Nombre<input value={name} onChange={e=>setName(e.target.value)} className="mt-1 w-full rounded-lg border px-3 py-2"/></label><label className="text-sm">Límite diario<input type="number" min={1} max={500} value={limit} onChange={e=>setLimit(+e.target.value)} className="mt-1 w-full rounded-lg border px-3 py-2"/></label><label className="text-sm">Desde<input type="number" min={0} max={23} value={start} onChange={e=>setStart(+e.target.value)} className="mt-1 w-full rounded-lg border px-3 py-2"/></label><label className="text-sm">Hasta<input type="number" min={1} max={24} value={end} onChange={e=>setEnd(+e.target.value)} className="mt-1 w-full rounded-lg border px-3 py-2"/></label><div className="text-sm">Días<div className="mt-1 flex gap-1">{daysText.map((x,d)=><button key={d} onClick={()=>setDays(v=>v.includes(d)?v.filter(n=>n!==d):[...v,d])} className={`h-9 w-9 rounded-lg ${days.includes(d)?'bg-indigo-600 text-white':'border'}`}>{x}</button>)}</div></div></div>
 <div className="mt-6 flex justify-between"><div><b>Flujo de contacto</b><p className="text-xs text-slate-500">Cada tarjeta es una acción y puede bifurcarse.</p></div><button onClick={()=>setSteps(v=>[...v,{channel:'task',delayHours:24,personalization:'template'}])} className="flex items-center gap-1 rounded-lg border px-3 py-2 text-sm"><Plus className="h-4 w-4"/>Paso</button></div>
 <div className="mt-3 space-y-4">{steps.map((s,i)=><div key={i} className="rounded-xl border bg-slate-50 p-4"><div className="flex gap-2"><span className="rounded bg-indigo-600 px-2 py-1 text-xs text-white">{i+1}</span><b className="mr-auto">{channels.find(c=>c[0]===s.channel)?.[1]}</b><button onClick={()=>move(i,-1)}><ArrowUp className="h-4 w-4"/></button><button onClick={()=>move(i,1)}><ArrowDown className="h-4 w-4"/></button><button onClick={()=>steps.length>1&&setSteps(v=>v.filter((_,j)=>j!==i))} className="text-red-600"><Trash2 className="h-4 w-4"/></button></div><div className="mt-3 grid gap-3 md:grid-cols-3"><Select label="Canal" value={s.channel} set={v=>change(i,{channel:v})} options={channels}/><label className="text-xs">Espera (horas)<input type="number" value={s.delayHours} onChange={e=>change(i,{delayHours:+e.target.value})} className="mt-1 w-full rounded-lg border px-3 py-2"/></label><Select label="Personalización" value={s.personalization||'template'} set={v=>change(i,{personalization:v})} options={[["template","Variables"],["ai_company","IA · empresa"],["ai_research","IA · investigación"]]}/></div>{s.channel==='email'&&<label className="mt-3 block text-xs">Asunto<input value={s.subject||''} onChange={e=>change(i,{subject:e.target.value})} className="mt-1 w-full rounded-lg border px-3 py-2"/></label>}<label className="mt-3 block text-xs">Mensaje<textarea value={s.templateBody||''} onChange={e=>change(i,{templateBody:e.target.value})} rows={3} className="mt-1 w-full rounded-lg border p-3"/></label>
 <details className="mt-3 rounded-lg border bg-white p-3"><summary className="cursor-pointer text-sm font-semibold"><GitBranch className="mr-1 inline h-4 w-4"/>Condición y A/B</summary><div className="mt-3 grid gap-2 md:grid-cols-4"><Select label="Condición" value={s.condition?.field||''} set={v=>change(i,{condition:v?{field:v,operator:'exists',onFalse:'skip'}:null})} options={[["","Siempre"],["email","Email"],["phone","Teléfono"],["linkedin","LinkedIn"],["score","Puntuación"],["status","Estado"]]}/>{s.condition?.field&&<><Select label="Operador" value={s.condition.operator||'exists'} set={v=>change(i,{condition:{...s.condition,operator:v}})} options={[["exists","Existe"],["missing","No existe"],["gte","≥"],["equals","Igual"]]}/><label className="text-xs">Valor<input value={String(s.condition.value||'')} onChange={e=>change(i,{condition:{...s.condition,value:e.target.value}})} className="mt-1 w-full rounded-lg border px-2 py-2"/></label><Select label="Si no" value={s.condition.onFalse||'skip'} set={v=>change(i,{condition:{...s.condition,onFalse:v}})} options={[["skip","Saltar"],["stop","Detener"]]}/></>}</div><button onClick={()=>change(i,{variants:[...(s.variants||[]),{body:''}]})} className="mt-3 rounded border px-2 py-1 text-xs">+ Variante</button>{s.variants?.map((v,j)=><textarea key={j} value={v.body||''} onChange={e=>change(i,{variants:s.variants?.map((x,k)=>k===j?{...x,body:e.target.value}:x)})} placeholder={`Variante ${String.fromCharCode(65+j)}`} className="mt-2 w-full rounded border p-2 text-sm"/>)}</details>{s.channel==='email'&&<label className="mt-3 flex gap-2 text-sm"><input type="checkbox" checked={!!s.requiresReview} onChange={e=>change(i,{requiresReview:e.target.checked})}/>Revisar antes de enviar</label>}</div>)}</div>
 <div className="mt-6 flex justify-end gap-2"><button onClick={onClose} className="rounded-xl border px-4 py-2">Cancelar</button><button disabled={saving||!name.trim()||!days.length||end<=start} onClick={()=>void save()} className="rounded-xl bg-indigo-600 px-5 py-2 font-semibold text-white disabled:opacity-50">{saving?'Guardando…':'Guardar flujo'}</button></div></div></div>;
}
function Select({label,value,set,options}:{label:string;value:string;set:(v:string)=>void;options:string[][]}){return <label className="text-xs">{label}<select value={value} onChange={e=>set(e.target.value)} className="mt-1 w-full rounded-lg border bg-white px-2 py-2">{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}
