"use client";
import { useEffect, useMemo, useState } from "react";
import { Check, Copy, ExternalLink, Linkedin, Mail, Pause, Play, Plus, Settings, Target, Upload } from "lucide-react";
import ProspectingCampaignEditor from "@/components/admin/ProspectingCampaignEditor";

type Step={channel:string;delayHours:number;templateBody?:string;subject?:string;requiresReview?:boolean};
type Prospect={id:string;firstName?:string;lastName?:string;companyName?:string;jobTitle?:string;email?:string;linkedinUrl?:string;status:string;currentStep:number};
type Activity={id:string;channel:string;action?:string;status:string;detail?:string;error?:string;createdAt?:string;payload?:{to?:string;subject?:string;body?:string};prospect?:Prospect};
type Campaign={id:string;name:string;status:string;dailyLimit:number;startHour?:number;endHour?:number;activeWeekdays?:number[];steps:Step[];prospects:Prospect[];activities:Activity[];stats:Record<string,number>;activityStats:Record<string,number>};
const labels:Record<string,string>={linkedin_visit:"Visitar LinkedIn",linkedin_connect:"Conectar en LinkedIn",linkedin_message:"Mensaje LinkedIn",email:"Email",whatsapp:"WhatsApp",task:"Tarea manual"};
const defaults:Step[]=[{channel:"linkedin_visit",delayHours:0,requiresReview:true},{channel:"linkedin_connect",delayHours:24,templateBody:"Hola {{firstName}}, me gustaría añadirte a mi red.",requiresReview:true},{channel:"linkedin_message",delayHours:48,templateBody:"Hola {{firstName}}, he visto tu trabajo en {{companyName}}. Tengo una idea concreta para ayudaros a captar más clientes. ¿Te la comparto?",requiresReview:true},{channel:"email",delayHours:72,subject:"Idea para {{companyName}}",templateBody:"Hola {{firstName}},\n\nHe preparado una idea específica para {{companyName}}. ¿Te viene bien que te la envíe?",requiresReview:false}];
const count=(s:Record<string,number>)=>Object.values(s||{}).reduce((a,b)=>a+b,0);

export default function ProspectingClient(){
 const [campaigns,setCampaigns]=useState<Campaign[]>([]),[selectedId,setSelectedId]=useState<string|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
 const [createOpen,setCreateOpen]=useState(false),[importOpen,setImportOpen]=useState(false),[editOpen,setEditOpen]=useState(false),[name,setName]=useState(""),[sourceUrl,setSourceUrl]=useState(""),[dailyLimit,setDailyLimit]=useState(30);
 const [csv,setCsv]=useState("firstName,lastName,companyName,jobTitle,linkedinUrl,email,phone,website\n");
 const selected=useMemo(()=>campaigns.find(c=>c.id===selectedId)||campaigns[0],[campaigns,selectedId]);
 const pending=selected?.activities.filter(a=>a.status==="awaiting_review")||[];
 async function load(id?:string){setLoading(true);try{const r=await fetch(`/api/v1/leads/prospecting${id?`?campaignId=${encodeURIComponent(id)}`:""}`,{cache:"no-store"});const b=await r.json();if(!r.ok)throw new Error(b?.error?.message||"No se pudo cargar");setCampaigns(b.campaigns||[]);if(id)setSelectedId(id)}catch(e){setError(e instanceof Error?e.message:"Error interno")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function create(){setSaving(true);try{const r=await fetch("/api/v1/leads/prospecting",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,source:sourceUrl?"linkedin":"csv",sourceUrl,objective:"meeting",dailyLimit,steps:defaults})});const b=await r.json();if(!r.ok)throw new Error(b?.error?.message||"No se pudo crear");setCreateOpen(false);setName("");await load(b.campaign.id)}catch(e){setError(e instanceof Error?e.message:"Error interno")}finally{setSaving(false)}}
 async function status(action:"activate"|"pause"|"resume"){if(!selected)return;const r=await fetch("/api/v1/leads/prospecting",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:selected.id,action})});if(!r.ok){const b=await r.json();setError(b?.error?.message||"No se pudo actualizar")}else await load(selected.id)}
 function rows(){const table=parseDelimited(csv);if(table.length<2)return[];const h=table[0].map(x=>x.trim());return table.slice(1).filter(r=>r.some(Boolean)).map(values=>Object.fromEntries(h.map((key,index)=>[key,values[index]?.trim()||""])))}
 async function importRows(){if(!selected)return;setSaving(true);try{const r=await fetch("/api/v1/leads/prospecting/import",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({campaignId:selected.id,rows:rows()})});const b=await r.json();if(!r.ok)throw new Error(b?.error?.message||"No se pudo importar");alert(`${b.imported} importados · ${b.duplicates} duplicados bloqueados`);setImportOpen(false);await load(selected.id)}catch(e){setError(e instanceof Error?e.message:"Error interno")}finally{setSaving(false)}}
 async function complete(id:string,action:"complete"|"replied"="complete"){const r=await fetch("/api/v1/leads/prospecting/activities",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({activityId:id,action})});if(!r.ok){const b=await r.json();setError(b?.error?.message||"No se pudo completar")}else if(selected)await load(selected.id)}
 async function markReply(prospectId:string){const r=await fetch("/api/v1/leads/prospecting/activities",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({prospectId,action:"replied"})});if(!r.ok){const b=await r.json();setError(b?.error?.message||"No se pudo registrar la respuesta")}else if(selected)await load(selected.id)}
 async function manageProspect(prospectId:string,action:"exclude"|"reactivate"|"retry"|"qualified"|"meeting"){const r=await fetch("/api/v1/leads/prospecting/prospects",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({prospectId,action})});if(!r.ok){const b=await r.json();setError(b?.error?.message||"No se pudo actualizar el prospecto")}else if(selected)await load(selected.id)}
 return <main className="min-h-screen bg-slate-50 p-4 md:p-8"><div className="mx-auto max-w-7xl">
  <header className="mb-6 flex flex-wrap justify-between gap-4"><div><div className="mb-2 inline-flex items-center gap-2 rounded-full bg-indigo-100 px-3 py-1 text-xs font-semibold text-indigo-700"><Target className="h-4 w-4"/> NV Prospección</div><h1 className="text-3xl font-bold">Prospección multicanal propia</h1><p className="mt-1 text-sm text-slate-600">Campañas y cadencias gestionadas por el Hub, sin depender de Waalaxy.</p></div><div className="flex gap-2"><a href="/admin/leads" className="rounded-xl border bg-white px-4 py-2 text-sm">NV Leads Pro</a><button onClick={()=>setCreateOpen(true)} className="flex items-center gap-2 rounded-xl bg-indigo-600 px-4 py-2 text-sm font-semibold text-white"><Plus className="h-4 w-4"/>Nueva campaña</button></div></header>
  {error&&<div className="mb-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
  <div className="mb-6 grid gap-3 md:grid-cols-4"><Metric label="Campañas activas" value={campaigns.filter(c=>c.status==="active").length}/><Metric label="Prospectos" value={campaigns.reduce((n,c)=>n+count(c.stats),0)}/><Metric label="Acciones pendientes" value={campaigns.reduce((n,c)=>n+(c.activityStats?.awaiting_review||0),0)}/><Metric label="Respuestas" value={campaigns.reduce((n,c)=>n+(c.stats.replied||0),0)}/></div>
  {loading?<Panel>Cargando…</Panel>:!campaigns.length?<Panel><Target className="mx-auto mb-3 h-10 w-10 text-indigo-400"/>Crea tu primera campaña propia.</Panel>:<div className="grid gap-5 lg:grid-cols-[300px,1fr]"><aside className="space-y-2">{campaigns.map(c=><button key={c.id} onClick={()=>void load(c.id)} className={`w-full rounded-xl border p-4 text-left ${selected?.id===c.id?"border-indigo-300 bg-indigo-50":"bg-white"}`}><div className="flex justify-between"><b>{c.name}</b><Status value={c.status}/></div><div className="mt-2 text-xs text-slate-500">{count(c.stats)} prospectos · {c.dailyLimit}/día</div></button>)}</aside>
  {selected&&<section className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-bold">{selected.name}</h2><p className="text-sm text-slate-500">Email automático · LinkedIn asistido y seguro</p></div><div className="flex gap-2"><button disabled={selected.status==="active"} title={selected.status==="active"?"Pausa la campaña para configurarla":"Configurar campaña"} onClick={()=>setEditOpen(true)} className="flex items-center gap-1 rounded-lg border px-3 py-2 text-sm disabled:cursor-not-allowed disabled:opacity-40"><Settings className="h-4 w-4"/>Configurar</button><button onClick={()=>setImportOpen(true)} className="flex items-center gap-1 rounded-lg border px-3 py-2 text-sm"><Upload className="h-4 w-4"/>Importar</button>{selected.status==="active"?<button onClick={()=>void status("pause")} className="flex items-center gap-1 rounded-lg bg-amber-100 px-3 py-2 text-sm"><Pause className="h-4 w-4"/>Pausar</button>:<button onClick={()=>void status(selected.status==="paused"?"resume":"activate")} className="flex items-center gap-1 rounded-lg bg-emerald-600 px-3 py-2 text-sm text-white"><Play className="h-4 w-4"/>Activar</button>}</div></div>
   <h3 className="mb-2 mt-6 text-sm font-semibold">Cadencia</h3><div className="flex gap-2 overflow-x-auto">{selected.steps.map((s,i)=><div key={i} className="min-w-40 rounded-xl border bg-slate-50 p-3"><div className="text-xs text-slate-500">Paso {i+1} · +{s.delayHours} h</div><b className="text-sm">{labels[s.channel]||s.channel}</b></div>)}</div>
   {selected.activities.length>0&&<details className="mt-5 rounded-xl border"><summary className="cursor-pointer p-3 text-sm font-semibold">Historial de actividad · {Object.values(selected.activityStats||{}).reduce((a,b)=>a+b,0)}</summary><div className="max-h-72 overflow-y-auto border-t">{selected.activities.slice(0,50).map(a=><div key={a.id} className="flex justify-between gap-3 border-b p-3 text-sm last:border-0"><div><b>{labels[a.channel]||a.channel}</b> · {[a.prospect?.firstName,a.prospect?.lastName].filter(Boolean).join(" ")||"Sin prospecto"}<div className="text-xs text-slate-500">{a.createdAt?new Date(a.createdAt).toLocaleString("es-ES"):""}</div>{a.error&&<div className="text-xs text-red-600">{a.error}</div>}</div><Status value={a.status}/></div>)}</div></details>}
   {pending.length>0&&<><h3 className="mb-2 mt-6 text-sm font-semibold">Acciones pendientes</h3><div className="space-y-3">{pending.map(a=><div key={a.id} className="rounded-xl border border-blue-200 bg-blue-50 p-4"><b>{labels[a.channel]||a.channel} · {[a.prospect?.firstName,a.prospect?.lastName].filter(Boolean).join(" ")}</b>{a.channel==="email"&&<div className="mt-2 rounded-lg border border-blue-100 bg-white p-3 text-sm"><p><b>Para:</b> {a.payload?.to||a.prospect?.email||"Sin destinatario"}</p><p><b>Asunto:</b> {a.payload?.subject||"Sin asunto"}</p></div>}{a.detail&&<p className="my-2 whitespace-pre-wrap text-sm">{a.detail}</p>}<div className="flex flex-wrap gap-2">{a.prospect?.linkedinUrl&&<a href={a.prospect.linkedinUrl} target="_blank" rel="noreferrer" className="flex items-center gap-1 rounded-lg border bg-white px-3 py-2 text-sm"><ExternalLink className="h-4 w-4"/>Abrir LinkedIn</a>}{a.detail&&<button onClick={()=>void navigator.clipboard.writeText(a.detail||"")} className="rounded-lg border bg-white p-2" title="Copiar texto"><Copy className="h-4 w-4"/></button>}<button onClick={()=>{if(a.channel!=="email"||window.confirm(`Se enviará este email a ${a.payload?.to||a.prospect?.email||"el destinatario"}. ¿Confirmas el envío?`))void complete(a.id)}} className="flex items-center gap-1 rounded-lg bg-blue-700 px-3 py-2 text-sm text-white"><Check className="h-4 w-4"/>{a.channel==="email"?"Aprobar y enviar email":"Realizada"}</button><button onClick={()=>void complete(a.id,"replied")} className="rounded-lg border border-blue-300 bg-white px-3 py-2 text-sm">Respondió</button></div></div>)}</div></>}
   <div className="mt-6 overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead><tr className="border-b text-xs uppercase text-slate-500"><th className="py-3">Persona</th><th>Empresa</th><th>Datos</th><th>Estado</th><th>Paso</th><th>Acciones</th></tr></thead><tbody>{selected.prospects.map(p=><tr key={p.id} className="border-b"><td className="py-3">{[p.firstName,p.lastName].filter(Boolean).join(" ")||"Sin nombre"}<small className="block text-slate-500">{p.jobTitle}</small></td><td>{p.companyName||"—"}</td><td><span className="flex gap-2">{p.linkedinUrl&&<Linkedin className="h-4 w-4 text-blue-700"/>}{p.email&&<Mail className="h-4 w-4"/>}</span></td><td><Status value={p.status}/></td><td>{Math.min(p.currentStep+1,selected.steps.length)}/{selected.steps.length}</td><td><div className="flex items-center gap-2">{!["replied","excluded"].includes(p.status)&&<button onClick={()=>void markReply(p.id)} className="rounded-lg border px-2 py-1 text-xs">Respondió</button>}<select defaultValue="" onChange={e=>{const action=e.target.value as "exclude"|"reactivate"|"retry"|"qualified"|"meeting";if(action)void manageProspect(p.id,action);e.currentTarget.value=""}} className="rounded-lg border bg-white px-2 py-1 text-xs"><option value="" disabled>Más…</option><option value="qualified">Cualificado</option><option value="meeting">Reunión</option><option value="exclude">Excluir</option><option value="reactivate">Reactivar</option>{p.status==="active"&&<option value="retry">Reintentar</option>}</select></div></td></tr>)}</tbody></table></div>
  </section>}</div>}
 </div>{createOpen&&<Modal title="Nueva campaña" close={()=>setCreateOpen(false)}><Field label="Nombre" value={name} set={setName}/><Field label="URL de búsqueda (referencia)" value={sourceUrl} set={setSourceUrl}/><p className="mt-2 text-xs text-slate-500">La URL no da acceso a tu cuenta ni extrae datos. Importa los contactos por CSV.</p><label className="mt-3 block text-sm">Límite diario<input type="number" min={1} max={500} value={dailyLimit} onChange={e=>setDailyLimit(Number(e.target.value))} className="mt-1 w-full rounded-lg border px-3 py-2"/></label><button disabled={saving||!name.trim()} onClick={()=>void create()} className="mt-5 w-full rounded-xl bg-indigo-600 py-2.5 font-semibold text-white disabled:opacity-50">Crear campaña</button></Modal>}
 {importOpen&&<Modal title="Importar prospectos" close={()=>setImportOpen(false)}><p className="mb-2 text-xs text-slate-500">Columnas admitidas: firstName, lastName, companyName, jobTitle, linkedinUrl, email, phone y website.</p><textarea value={csv} onChange={e=>setCsv(e.target.value)} rows={10} className="w-full rounded-xl border p-3 font-mono text-xs"/>{rows().length>0&&<div className="mt-3 rounded-xl border bg-slate-50 p-3"><div className="mb-2 text-xs font-semibold">Vista previa · {rows().length} contactos</div>{rows().slice(0,5).map((row,index)=><div key={index} className="truncate border-t py-1 text-xs">{[row.firstName,row.lastName].filter(Boolean).join(" ")||"Sin nombre"} · {row.companyName||"Sin empresa"} · {row.email||row.linkedinUrl||row.phone}</div>)}</div>}<button disabled={saving||!rows().length} onClick={()=>void importRows()} className="mt-4 w-full rounded-xl bg-indigo-600 py-2.5 font-semibold text-white">Importar {rows().length}</button></Modal>}{editOpen&&selected&&<ProspectingCampaignEditor campaign={selected} onClose={()=>setEditOpen(false)} onSaved={()=>load(selected.id)}/>}</main>
}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded-2xl border bg-white p-4"><small className="text-slate-500">{label}</small><div className="mt-1 text-2xl font-bold">{value}</div></div>}
function Status({value}:{value:string}){const m:Record<string,string>={active:"Activa",paused:"Pausada",draft:"Borrador",pending:"Pendiente",waiting_action:"Acción pendiente",awaiting_review:"Por revisar",processing:"Procesando",completed:"Completado",sent:"Enviado",failed:"Fallido",skipped:"Omitido",qualified:"Cualificado",meeting:"Reunión",excluded:"Excluido",replied:"Respondido"};return <span className="rounded-full bg-slate-100 px-2 py-1 text-xs">{m[value]||value}</span>}
function Panel({children}:{children:React.ReactNode}){return <div className="rounded-2xl border bg-white p-10 text-center text-slate-500">{children}</div>}
function Field({label,value,set}:{label:string;value:string;set:(v:string)=>void}){return <label className="mt-3 block text-sm">{label}<input value={value} onChange={e=>set(e.target.value)} className="mt-1 w-full rounded-lg border px-3 py-2"/></label>}
function Modal({title,children,close}:{title:string;children:React.ReactNode;close:()=>void}){return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4" onMouseDown={close}><div className="w-full max-w-xl rounded-2xl bg-white p-5" onMouseDown={e=>e.stopPropagation()}><div className="mb-4 flex justify-between"><h2 className="text-lg font-bold">{title}</h2><button onClick={close}>×</button></div>{children}</div></div>}
function parseDelimited(text:string){const first=text.split(/\r?\n/,1)[0]||"";const delimiter=first.includes("\t")?"\t":first.split(";").length>first.split(",").length?";":",";const rows:string[][]=[];let row:string[]=[],cell="",quoted=false;for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(ch===delimiter&&!quoted){row.push(cell);cell=""}else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&text[i+1]==='\n')i++;row.push(cell);rows.push(row);row=[];cell=""}else cell+=ch}if(cell||row.length){row.push(cell);rows.push(row)}return rows}
