"use client";
import { useEffect, useState } from "react";
import { BarChart3, Inbox, ScanSearch, Sparkles, Users } from "lucide-react";
type P={id:string;firstName?:string;lastName?:string;companyName?:string;score?:number;resolutionStatus?:string};
type D={messages:Array<{id:string;channel:string;body:string;createdAt:string;prospect:P}>;members:Array<{id:string;name?:string;email:string;role:string}>;analytics:{total:number;avgScore:number;attributedValue:number;funnel:Array<{status:string;count:number}>;byChannel:Record<string,{actions:number;sent:number;replies:number}>}};
const tabs=[['intelligence','Inteligencia',ScanSearch],['inbox','Bandeja',Inbox],['analytics','Analítica',BarChart3],['team','Equipo',Users],['sources','Fuentes',Sparkles]] as const;
export default function Suite({campaignId,prospects,onChanged}:{campaignId:string;prospects:P[];onChanged:()=>Promise<void>}){
 const [tab,setTab]=useState<(typeof tabs)[number][0]>('intelligence'),[data,setData]=useState<D|null>(null),[selected,setSelected]=useState<string[]>([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 async function load(){const r=await fetch(`/api/v1/leads/prospecting/suite?campaignId=${encodeURIComponent(campaignId)}`,{cache:'no-store'});if(r.ok)setData(await r.json())} useEffect(()=>{void load()},[campaignId]);
 async function run(action:'enrich'|'score'|'assign',userId?:string){setBusy(true);setNotice('');try{const r=await fetch('/api/v1/leads/prospecting/suite',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,prospectIds:selected.length?selected:prospects.map(p=>p.id),...(action==='assign'?{userId}: {})})});const b=await r.json();if(!r.ok)throw new Error(b?.error?.message||'No se pudo completar');setNotice(action==='enrich'?`${b.enriched} perfiles resueltos de ${b.processed}`:`${b.updated} registros actualizados`);await Promise.all([load(),onChanged()])}catch(e){setNotice(e instanceof Error?e.message:'Error interno')}finally{setBusy(false)}}
 return <div className="mt-6 rounded-2xl border border-indigo-200 bg-indigo-50/40 p-4"><div className="flex gap-2 overflow-x-auto border-b pb-3">{tabs.map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className={`flex items-center gap-2 whitespace-nowrap rounded-lg px-3 py-2 text-sm font-semibold ${tab===id?'bg-indigo-600 text-white':'bg-white'}`}><Icon className="h-4 w-4"/>{label}</button>)}</div>{notice&&<p className="mt-3 rounded-lg bg-white p-2 text-sm">{notice}</p>}
 {tab==='intelligence'&&<div className="mt-4"><div className="flex flex-wrap gap-2"><b className="mr-auto">Enriquecimiento en cascada, resolución y scoring</b><button disabled={busy||!prospects.length} onClick={()=>void run('enrich')} className="rounded-lg bg-indigo-600 px-3 py-2 text-sm text-white">Resolver y enriquecer</button><button disabled={busy||!prospects.length} onClick={()=>void run('score')} className="rounded-lg border bg-white px-3 py-2 text-sm">Recalcular score</button></div><p className="mt-1 text-xs text-slate-600">Hunter → Apollo → datos propios. Se guardan fuente, candidatos y confianza; nunca se inventan contactos.</p><div className="mt-3 max-h-64 overflow-auto rounded-xl border bg-white">{prospects.map(p=><label key={p.id} className="flex gap-3 border-b p-3 text-sm"><input type="checkbox" checked={selected.includes(p.id)} onChange={e=>setSelected(v=>e.target.checked?[...v,p.id]:v.filter(id=>id!==p.id))}/><span className="min-w-0 flex-1 truncate">{[p.firstName,p.lastName].filter(Boolean).join(' ')||'Sin nombre'} · {p.companyName||'Sin empresa'}</span><span>Score {p.score||0}</span><small>{p.resolutionStatus||'sin resolver'}</small></label>)}</div></div>}
 {tab==='inbox'&&<div className="mt-4"><b>Bandeja multicanal</b><p className="text-xs text-slate-500">LinkedIn · email · WhatsApp · teléfono</p><div className="mt-3 max-h-80 overflow-auto rounded-xl border bg-white">{!data?.messages.length?<p className="p-6 text-center text-sm text-slate-500">Sin conversaciones sincronizadas.</p>:data.messages.map(m=><div key={m.id} className="border-b p-3"><small>{m.channel} · {[m.prospect.firstName,m.prospect.lastName].filter(Boolean).join(' ')} · {new Date(m.createdAt).toLocaleString('es-ES')}</small><p className="mt-1 text-sm">{m.body}</p></div>)}</div></div>}
 {tab==='analytics'&&<div className="mt-4"><div className="grid gap-3 md:grid-cols-3"><Metric label="Prospectos" value={data?.analytics.total||0}/><Metric label="Score medio" value={data?.analytics.avgScore||0}/><Metric label="Valor atribuido" value={`${(data?.analytics.attributedValue||0).toLocaleString('es-ES')} €`}/></div><div className="mt-3 grid gap-3 md:grid-cols-2"><Box title="Embudo">{data?.analytics.funnel.map(x=><Row key={x.status} label={x.status} value={x.count}/>)}</Box><Box title="Atribución por canal">{Object.entries(data?.analytics.byChannel||{}).map(([k,v])=><Row key={k} label={k} value={`${v.sent} salidas · ${v.replies} respuestas`}/>)}</Box></div></div>}
 {tab==='team'&&<div className="mt-4"><b>Gestión de equipos</b><p className="text-xs text-slate-500">Asigna la selección o la campaña completa.</p><div className="mt-3 grid gap-2 md:grid-cols-2">{data?.members.map(m=><button key={m.id} onClick={()=>void run('assign',m.id)} className="rounded-xl border bg-white p-3 text-left"><b>{m.name||m.email}</b><small className="block">{m.email} · {m.role}</small></button>)}</div></div>}
 {tab==='sources'&&<div className="mt-4"><b>Nuevas fuentes de LinkedIn</b><p className="mt-1 text-sm text-slate-600">Búsquedas y Sales Navigator, miembros visibles de grupos y eventos, asistentes e interacciones en publicaciones. La extensión conserva URL, origen y fecha para resolver cada perfil después.</p><div className="mt-3 grid gap-2 md:grid-cols-3">{['Búsquedas y Sales Navigator','Grupos y eventos','Interacciones en publicaciones'].map(x=><div key={x} className="rounded-xl border bg-white p-3 text-sm font-semibold">{x}</div>)}</div></div>}</div>;
}
function Metric({label,value}:{label:string;value:string|number}){return <div className="rounded-xl border bg-white p-4"><small>{label}</small><div className="text-2xl font-bold">{value}</div></div>} function Box({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-xl border bg-white p-4"><b>{title}</b>{children}</section>} function Row({label,value}:{label:string;value:string|number}){return <div className="mt-2 flex justify-between text-sm"><span>{label}</span><b>{value}</b></div>}
