"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Loader2, Plus, Save, ThumbsDown, ThumbsUp, TrendingUp } from "lucide-react";

type Lead = { id: string; externalLeadId: string; contactName: string | null; campaignName: string | null; status: string; revenueCents: number; qualityScore: number | null; occurredAt: string };
type Metrics = { total: number; qualified: number; appointments: number; proposals: number; won: number; invalid: number; revenue: number; qualificationRate: number; closeRate: number };
type Profile = { clientId: string | null; displayName: string; monthlyBudgetCents: number; targetLeads: number | null; targetQualifiedCplCents: number | null; salesValueCents: number | null; businessBrief: string | null };
const stages = [["new", "Nuevo"], ["contacted", "Contactado"], ["qualified", "Cualificado"], ["appointment", "Cita"], ["proposal", "Presupuesto"], ["won", "Venta"], ["lost", "Perdido"], ["invalid", "Inválido"]];
const euro = (cents: number) => new Intl.NumberFormat("es-ES", { style: "currency", currency: "EUR" }).format(cents / 100);

export default function MetaAttributionPanel({ accountId, accountName, connectionId, campaigns, spend }: { accountId: string; accountName: string; connectionId: string; campaigns: Array<{ id: string; name: string }>; spend: number }) {
  const [items, setItems] = useState<Lead[]>([]); const [metrics, setMetrics] = useState<Metrics | null>(null); const [profile, setProfile] = useState<Profile | null>(null); const [busy, setBusy] = useState(false); const [syncing, setSyncing] = useState(false); const [message, setMessage] = useState<string | null>(null); const [adding, setAdding] = useState(false);
  const [clients, setClients] = useState<Array<{ id: string; name: string }>>([]);
  const [form, setForm] = useState({ contactName: "", externalLeadId: "", campaignId: "", revenue: "" });
  const load = useCallback(async () => { setBusy(true); try { const response = await fetch(`/api/v1/meta-attribution?accountId=${encodeURIComponent(accountId)}`, { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data?.error?.message); setItems(data.items ?? []); setMetrics(data.metrics); setProfile(data.profile ?? { clientId: null, displayName: accountName, monthlyBudgetCents: 0, targetLeads: null, targetQualifiedCplCents: null, salesValueCents: null, businessBrief: null }); } catch (error: any) { setMessage(error.message ?? "No se pudo cargar la atribución"); } finally { setBusy(false); } }, [accountId, accountName]);
  useEffect(() => { void load(); void fetch("/api/v1/clients?limit=200").then((r) => r.json()).then((data) => setClients(data.items ?? data.clients ?? [])).catch(() => {}); }, [load]);
  useEffect(() => { let active = true; setSyncing(true); void fetch("/api/v1/meta-leads/sync", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ adAccountId: accountId, accountName, connectionId }) }).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data?.error?.message ?? "No se pudieron sincronizar los leads"); if (active) { setMessage(data.imported ? `${data.imported} lead(s) nuevo(s) importados automáticamente.` : "Leads sincronizados con Meta."); await load(); } }).catch((error) => { if (active) setMessage(String(error?.message ?? error)); }).finally(() => { if (active) setSyncing(false); }); return () => { active = false; }; }, [accountId, accountName, connectionId, load]);
  const commercial = useMemo(() => metrics ? { ...metrics, costQualified: metrics.qualified ? spend / metrics.qualified : null, costSale: metrics.won ? spend / metrics.won : null, roas: spend > 0 ? metrics.revenue / spend : null } : null, [metrics, spend]);

  async function addLead() { const campaign = campaigns.find((item) => item.id === form.campaignId); setBusy(true); setMessage(null); try { const response = await fetch("/api/v1/meta-attribution", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "lead", adAccountId: accountId, externalLeadId: form.externalLeadId || `manual-${Date.now()}`, contactName: form.contactName || null, campaignId: campaign?.id ?? null, campaignName: campaign?.name ?? null, revenueCents: Math.round(Number(form.revenue || 0) * 100) }) }); const data = await response.json(); if (!response.ok) throw new Error(data?.error?.message); setForm({ contactName: "", externalLeadId: "", campaignId: "", revenue: "" }); setAdding(false); await load(); } catch (error: any) { setMessage(error.message ?? "No se pudo guardar"); } finally { setBusy(false); } }
  async function updateLead(item: Lead, status: string, revenueCents = item.revenueCents) { setBusy(true); try { const response = await fetch(`/api/v1/meta-attribution/${item.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status, revenueCents }) }); const data = await response.json(); if (!response.ok) throw new Error(data?.error?.message ?? "No se pudo actualizar"); if (status === "qualified") setMessage(data.feedback?.sent ? "Lead marcado como bueno y señal QualifiedLead enviada a Meta." : `Lead marcado como bueno. Meta aún no puede recibir la señal: ${data.feedback?.reason ?? "dataset no asociado"}.`); if (status === "invalid") setMessage("Lead marcado como malo. Se usará para medir calidad y no se enviará como conversión positiva."); await load(); } catch (error: any) { setMessage(error.message); } finally { setBusy(false); } }
  async function saveProfile() { if (!profile) return; setBusy(true); try { const response = await fetch("/api/v1/meta-attribution", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "profile", adAccountId: accountId, displayName: profile.displayName || accountName, clientId: profile.clientId, metaConnectionId: connectionId, monthlyBudgetCents: profile.monthlyBudgetCents, targetLeads: profile.targetLeads, targetQualifiedCplCents: profile.targetQualifiedCplCents, salesValueCents: profile.salesValueCents, businessBrief: profile.businessBrief }) }); if (!response.ok) throw new Error("No se pudo guardar la configuración"); setMessage("Objetivos y memoria guardados."); } catch (error: any) { setMessage(error.message); } finally { setBusy(false); } }

  return <section className="mb-5 rounded-xl border bg-white p-5"><div className="mb-4 flex flex-wrap items-start justify-between gap-3"><div><h2 className="flex items-center gap-2 text-lg font-bold"><TrendingUp className="h-5 w-5 text-indigo-600" /> Atribución comercial real</h2><p className="text-sm text-slate-500">Los leads de Meta se importan automáticamente. Marca Bueno o Malo para medir la calidad y devolver a Meta las conversiones cualificadas.</p></div><div className="flex items-center gap-2">{syncing && <span className="inline-flex items-center gap-1 text-xs text-slate-500"><Loader2 className="h-3.5 w-3.5 animate-spin" /> Sincronizando Meta</span>}<button onClick={() => setAdding(!adding)} className="inline-flex items-center gap-2 rounded-lg bg-indigo-600 px-3 py-2 text-sm font-semibold text-white"><Plus className="h-4 w-4" /> Registrar lead</button></div></div>
    {commercial && <div className="mb-5 grid gap-2 sm:grid-cols-3 lg:grid-cols-6">{[["Leads registrados", commercial.total], ["Cualificados", commercial.qualified], ["Ventas", commercial.won], ["Coste/cualificado", commercial.costQualified === null ? "—" : `${commercial.costQualified.toFixed(2)} €`], ["Coste/venta", commercial.costSale === null ? "—" : `${commercial.costSale.toFixed(2)} €`], ["ROAS real", commercial.roas === null ? "—" : `${commercial.roas.toFixed(2)}x`]].map(([label, value]) => <div key={label} className="rounded-lg bg-slate-50 p-3"><div className="text-xs text-slate-500">{label}</div><div className="mt-1 text-lg font-bold">{value}</div></div>)}</div>}
    {adding && <div className="mb-4 grid gap-2 rounded-lg border border-indigo-200 bg-indigo-50 p-3 md:grid-cols-5"><input placeholder="Nombre del lead" value={form.contactName} onChange={(e) => setForm({ ...form, contactName: e.target.value })} className="rounded border px-2 py-2 text-sm" /><input placeholder="ID Meta (opcional)" value={form.externalLeadId} onChange={(e) => setForm({ ...form, externalLeadId: e.target.value })} className="rounded border px-2 py-2 text-sm" /><select value={form.campaignId} onChange={(e) => setForm({ ...form, campaignId: e.target.value })} className="rounded border px-2 py-2 text-sm"><option value="">Campaña desconocida</option>{campaigns.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><input type="number" min="0" step="0.01" placeholder="Valor venta €" value={form.revenue} onChange={(e) => setForm({ ...form, revenue: e.target.value })} className="rounded border px-2 py-2 text-sm" /><button disabled={busy} onClick={() => void addLead()} className="rounded bg-slate-900 px-3 py-2 text-sm font-semibold text-white">Guardar</button></div>}
    {message && <div className="mb-3 rounded bg-amber-50 p-2 text-sm text-amber-800">{message}</div>}
    <div className="mb-5 overflow-x-auto rounded-lg border"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="p-3">Lead</th><th className="p-3">Campaña</th><th className="p-3">Calidad</th><th className="p-3">Etapa</th><th className="p-3">Valor</th></tr></thead><tbody className="divide-y">{items.slice(0, 50).map((item) => <tr key={item.id}><td className="p-3 font-medium">{item.contactName || item.externalLeadId}</td><td className="max-w-64 truncate p-3 text-slate-600">{item.campaignName || "Sin atribuir"}</td><td className="p-3"><div className="flex gap-1"><button disabled={busy} onClick={() => void updateLead(item, "qualified")} className={`inline-flex items-center gap-1 rounded px-2 py-1 text-xs font-semibold ${["qualified", "appointment", "proposal", "won"].includes(item.status) ? "bg-emerald-600 text-white" : "border text-emerald-700"}`}><ThumbsUp className="h-3.5 w-3.5" /> Bueno</button><button disabled={busy} onClick={() => void updateLead(item, "invalid")} className={`inline-flex items-center gap-1 rounded px-2 py-1 text-xs font-semibold ${item.status === "invalid" ? "bg-red-600 text-white" : "border text-red-700"}`}><ThumbsDown className="h-3.5 w-3.5" /> Malo</button></div></td><td className="p-3"><select value={item.status} disabled={busy} onChange={(e) => void updateLead(item, e.target.value)} className="rounded border px-2 py-1">{stages.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></td><td className="p-3"><input aria-label="Valor de venta" className="w-28 rounded border px-2 py-1" type="number" min="0" step="0.01" defaultValue={item.revenueCents / 100} onBlur={(e) => void updateLead(item, item.status, Math.round(Number(e.target.value) * 100))} /> <span className="text-xs text-slate-400">{item.status === "won" ? euro(item.revenueCents) : ""}</span></td></tr>)}</tbody></table>{!items.length && !busy && <div className="p-6 text-center text-sm text-slate-500">Todavía no hay leads comerciales registrados para esta cuenta.</div>}{busy && <div className="flex justify-center p-4"><Loader2 className="h-5 w-5 animate-spin" /></div>}</div>
    {profile && <details className="rounded-lg border"><summary className="cursor-pointer p-3 font-semibold">Objetivos, presupuesto y memoria del cliente</summary><div className="grid gap-3 border-t p-3 md:grid-cols-4"><label className="text-xs text-slate-500">Presupuesto mensual (€)<input type="number" value={profile.monthlyBudgetCents / 100} onChange={(e) => setProfile({ ...profile, monthlyBudgetCents: Math.round(Number(e.target.value) * 100) })} className="mt-1 w-full rounded border px-2 py-2 text-sm" /></label><label className="text-xs text-slate-500">Objetivo de leads<input type="number" value={profile.targetLeads ?? ""} onChange={(e) => setProfile({ ...profile, targetLeads: e.target.value ? Number(e.target.value) : null })} className="mt-1 w-full rounded border px-2 py-2 text-sm" /></label><label className="text-xs text-slate-500">CPL cualificado objetivo (€)<input type="number" value={(profile.targetQualifiedCplCents ?? 0) / 100 || ""} onChange={(e) => setProfile({ ...profile, targetQualifiedCplCents: e.target.value ? Math.round(Number(e.target.value) * 100) : null })} className="mt-1 w-full rounded border px-2 py-2 text-sm" /></label><label className="text-xs text-slate-500">Valor medio de venta (€)<input type="number" value={(profile.salesValueCents ?? 0) / 100 || ""} onChange={(e) => setProfile({ ...profile, salesValueCents: e.target.value ? Math.round(Number(e.target.value) * 100) : null })} className="mt-1 w-full rounded border px-2 py-2 text-sm" /></label><label className="text-xs text-slate-500 md:col-span-4">Brief y aprendizajes del negocio<textarea value={profile.businessBrief ?? ""} onChange={(e) => setProfile({ ...profile, businessBrief: e.target.value })} rows={3} className="mt-1 w-full rounded border px-2 py-2 text-sm" placeholder="Oferta, márgenes, públicos, objeciones, restricciones de marca…" /></label><button onClick={() => void saveProfile()} disabled={busy} className="inline-flex items-center justify-center gap-2 rounded bg-slate-900 px-3 py-2 text-sm font-semibold text-white"><Save className="h-4 w-4" /> Guardar objetivos</button></div></details>}
  </section>;
}
