"use client";
import { useState } from "react";
import { AlertTriangle, FlaskConical, Loader2 } from "lucide-react";

export default function MetaCreativeLab({ accountId, campaigns, monitoring }: { accountId: string; campaigns: any[]; monitoring: any }) {
  const [result, setResult] = useState<any>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const anomalies = [
    monitoring.leadChangePct !== null && monitoring.leadChangePct <= -20 ? { severity: "high", text: `Caída de leads del ${Math.abs(monitoring.leadChangePct).toFixed(0)}% en el último periodo.` } : null,
    monitoring.spend > 0 && monitoring.leads === 0 ? { severity: "high", text: "Hay gasto pero ningún lead atribuido: posible incidencia de medición o formulario." } : null,
    ...campaigns.filter((campaign) => campaign.impressions >= 1000 && campaign.ctr < 0.8).map((campaign) => ({ severity: "medium", text: `CTR bajo en ${campaign.name} (${campaign.ctr.toFixed(2)}%).` }))
  ].filter(Boolean) as Array<{ severity: string; text: string }>;
  async function generate() { setBusy(true); setError(null); try { const attribution = await fetch(`/api/v1/meta-attribution?accountId=${encodeURIComponent(accountId)}`).then((r) => r.json()); const response = await fetch("/api/v1/meta-creative-lab", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ adAccountId: accountId, campaigns, commercial: attribution.metrics, brief: attribution.profile?.businessBrief ?? "" }) }); const data = await response.json(); if (!response.ok) throw new Error(data?.error?.message ?? "No se pudo generar el laboratorio"); setResult(data); } catch (cause: any) { setError(cause.message); } finally { setBusy(false); } }
  return <section className="mb-5 grid gap-5 xl:grid-cols-2"><div className="rounded-xl border bg-white p-5"><div className="mb-3 flex items-start justify-between gap-3"><div><h2 className="flex items-center gap-2 text-lg font-bold"><FlaskConical className="h-5 w-5 text-violet-600" /> Laboratorio creativo</h2><p className="text-sm text-slate-500">Hipótesis y pruebas controladas que cambian una sola variable.</p></div><button onClick={() => void generate()} disabled={busy} className="rounded-lg bg-violet-600 px-3 py-2 text-xs font-semibold text-white disabled:opacity-50">{busy ? <Loader2 className="h-4 w-4 animate-spin" /> : "Diseñar experimentos"}</button></div>{error && <div className="rounded bg-red-50 p-2 text-sm text-red-700">{error}</div>}{result?.patterns?.length > 0 && <div className="mb-3 rounded bg-violet-50 p-3 text-sm"><b>Lecturas prudentes:</b><ul className="mt-1 list-disc pl-5">{result.patterns.map((item: string) => <li key={item}>{item}</li>)}</ul></div>}<div className="space-y-2">{result?.experiments?.map((item: any, index: number) => <details key={`${item.hypothesis}-${index}`} className="rounded-lg border"><summary className="cursor-pointer p-3 font-semibold">{item.hypothesis}</summary><div className="space-y-1 border-t p-3 text-sm"><div><b>Control:</b> {item.control}</div><div><b>Variante:</b> {item.variant}</div><div><b>Métrica:</b> {item.metric}</div><div><b>Regla mínima:</b> {item.minimumRule}</div></div></details>)}</div>{!result && !busy && <div className="rounded-lg border border-dashed p-5 text-center text-sm text-slate-500">La IA preparará pruebas A/B utilizando la memoria y los resultados comerciales del cliente.</div>}</div><div className="rounded-xl border bg-white p-5"><h2 className="mb-1 flex items-center gap-2 text-lg font-bold"><AlertTriangle className="h-5 w-5 text-amber-600" /> Radar de anomalías</h2><p className="mb-3 text-sm text-slate-500">Incidencias de rendimiento o medición que requieren revisión.</p><div className="space-y-2">{anomalies.map((item, index) => <div key={`${item.text}-${index}`} className={`rounded-lg border p-3 text-sm ${item.severity === "high" ? "border-red-200 bg-red-50 text-red-800" : "border-amber-200 bg-amber-50 text-amber-800"}`}>{item.text}</div>)}{!anomalies.length && <div className="rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800">No se detectan anomalías críticas en los datos disponibles.</div>}</div><p className="mt-3 text-xs text-slate-500">El radar no confunde ausencia de datos con buen rendimiento: los fallos de tracking se señalan por separado.</p></div></section>;
}
