"use client";
import { useEffect, useMemo, useState } from "react";
import { Activity, BriefcaseBusiness, Printer } from "lucide-react";

export default function MetaIntelligencePanel({ accountId, accountName, monitoring }: { accountId: string; accountName: string; monitoring: { leads: number; spend: number; cpl: number | null; leadChangePct: number | null } }) {
  const [attribution, setAttribution] = useState<any>(null); const [portfolio, setPortfolio] = useState<any[]>([]);
  useEffect(() => { void Promise.all([fetch(`/api/v1/meta-attribution?accountId=${encodeURIComponent(accountId)}`, { cache: "no-store" }).then((r) => r.json()), fetch("/api/v1/meta-portfolio", { cache: "no-store" }).then((r) => r.json())]).then(([a, p]) => { setAttribution(a); setPortfolio(p.items ?? []); }); }, [accountId]);
  const intelligence = useMemo(() => {
    if (!attribution) return null; const profile = attribution.profile; const metrics = attribution.metrics;
    const diagnosis: Array<{ phase: string; status: string; detail: string }> = [];
    if (monitoring.leads === 0 && monitoring.spend > 0) diagnosis.push({ phase: "Medición / captación", status: "critical", detail: "Hay inversión pero no se atribuyen leads. Verifica eventos y formularios antes de optimizar anuncios." });
    if (metrics.total && metrics.qualificationRate < 20) diagnosis.push({ phase: "Calidad", status: "warning", detail: `Sólo el ${metrics.qualificationRate.toFixed(0)}% de los leads registrados se cualifica. Revisa promesa, formulario y segmentación.` });
    if (metrics.qualified >= 5 && metrics.closeRate < 10) diagnosis.push({ phase: "Venta", status: "warning", detail: "La captación produce oportunidades, pero el cierre es bajo. El problema puede estar en velocidad de respuesta, seguimiento u oferta." });
    if (!diagnosis.length) diagnosis.push({ phase: "Embudo", status: "healthy", detail: metrics.total ? "No se detecta un cuello de botella crítico con los datos registrados." : "Registra las etapas comerciales para localizar el cuello de botella real." });
    return { profile, metrics, diagnosis };
  }, [attribution, monitoring]);
  if (!intelligence) return null;
  return <><section className="mb-5 rounded-xl border bg-white p-5"><h2 className="mb-3 flex items-center gap-2 text-lg font-bold"><Activity className="h-5 w-5 text-indigo-600" /> Diagnóstico del embudo</h2><div className="space-y-2">{intelligence.diagnosis.map((item) => <div key={item.phase} className={`rounded-lg border p-3 ${item.status === "critical" ? "border-red-200 bg-red-50" : item.status === "warning" ? "border-amber-200 bg-amber-50" : "border-emerald-200 bg-emerald-50"}`}><div className="font-semibold">{item.phase}</div><div className="text-sm text-slate-600">{item.detail}</div></div>)}</div><p className="mt-3 text-xs text-slate-500">Las previsiones mensuales permanecen desactivadas hasta disponer de datos de mes en curso completos y conciliados con Meta.</p></section>
    <section className="mb-5 rounded-xl border bg-white p-5"><div className="mb-4 flex flex-wrap justify-between gap-3"><div><h2 className="flex items-center gap-2 text-lg font-bold"><BriefcaseBusiness className="h-5 w-5 text-indigo-600" /> Control general de clientes META</h2><p className="text-sm text-slate-500">Salud comercial de las cuentas que ya tienen perfil y objetivos configurados.</p></div><button onClick={() => window.print()} className="inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-sm font-semibold"><Printer className="h-4 w-4" /> Informe imprimible</button></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{portfolio.map((item) => <div key={item.profile.id} className="rounded-lg border p-3"><div className="flex items-center justify-between"><b>{item.profile.displayName}</b><span className={`h-3 w-3 rounded-full ${item.health === "risk" ? "bg-red-500" : item.health === "attention" ? "bg-amber-500" : "bg-emerald-500"}`} /></div><div className="mt-2 grid grid-cols-3 gap-1 text-center text-xs"><div><b className="block text-base">{item.metrics.total}</b>Leads</div><div><b className="block text-base">{item.metrics.qualified}</b>Cualificados</div><div><b className="block text-base">{item.metrics.won}</b>Ventas</div></div>{item.alerts.map((alert: string) => <div key={alert} className="mt-2 rounded bg-amber-50 p-1.5 text-xs text-amber-800">{alert}</div>)}</div>)}</div>{!portfolio.length && <div className="rounded-lg border border-dashed p-5 text-center text-sm text-slate-500">Guarda objetivos en una cuenta para añadirla al control general.</div>}<div className="mt-4 rounded-lg bg-slate-50 p-3 text-sm"><b>Resumen de {accountName}:</b> {monitoring.leads} leads Meta, {intelligence.metrics.qualified} cualificados, {intelligence.metrics.won} ventas y {new Intl.NumberFormat("es-ES", { style: "currency", currency: "EUR" }).format(intelligence.metrics.revenue)} de facturación atribuida.</div></section></>;
}
