"use client";
import { useCallback, useEffect, useState } from "react";
import { Bot, Check, Loader2, RefreshCw, X } from "lucide-react";

type Proposal = { id: string; kind: string; priority: string; title: string; rationale: string; proposedAction: { description?: string }; expectedImpact?: { description?: string } | null; confidence: number; status: string };
export default function MetaDirectorPanel({ accountId, monitoring, campaigns }: { accountId: string; monitoring: any; campaigns: any[] }) {
  const [items, setItems] = useState<Proposal[]>([]); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null);
  const load = useCallback(async () => { const response = await fetch(`/api/v1/meta-director?accountId=${encodeURIComponent(accountId)}`, { cache: "no-store" }); const data = await response.json(); if (response.ok) setItems(data.items ?? []); }, [accountId]);
  useEffect(() => { void load(); }, [load]);
  async function generate() { setBusy(true); setMessage(null); try { const attributionResponse = await fetch(`/api/v1/meta-attribution?accountId=${encodeURIComponent(accountId)}`, { cache: "no-store" }); const attribution = await attributionResponse.json(); const response = await fetch("/api/v1/meta-director", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ adAccountId: accountId, monitoring, commercial: attribution.metrics, profile: attribution.profile, campaigns }) }); const data = await response.json(); if (!response.ok) throw new Error(data?.error?.message ?? "No se pudo generar el plan"); setItems(data.items ?? []); } catch (error: any) { setMessage(error.message); } finally { setBusy(false); } }
  async function decide(id: string, decision: "approved" | "rejected") { setBusy(true); const response = await fetch(`/api/v1/meta-director/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ decision }) }); const data = await response.json(); setMessage(data.message ?? (response.ok ? "Decisión guardada" : "No se pudo guardar")); await load(); setBusy(false); }
  return <section className="mb-5 rounded-xl border border-indigo-200 bg-gradient-to-br from-indigo-50 to-white p-5"><div className="mb-4 flex flex-wrap items-start justify-between gap-3"><div><h2 className="flex items-center gap-2 text-lg font-bold"><Bot className="h-5 w-5 text-indigo-600" /> Director IA</h2><p className="text-sm text-slate-500">Decisiones basadas en rendimiento y resultados comerciales. Aprobar no ejecuta cambios económicos automáticamente.</p></div><button onClick={() => void generate()} disabled={busy} className="inline-flex items-center gap-2 rounded-lg bg-indigo-600 px-3 py-2 text-sm font-semibold text-white disabled:opacity-50">{busy ? <Loader2 className="h-4 w-4 animate-spin" /> : <RefreshCw className="h-4 w-4" />} Generar plan actualizado</button></div>{message && <div className="mb-3 rounded bg-white p-2 text-sm text-slate-700">{message}</div>}<div className="grid gap-3 lg:grid-cols-2">{items.filter((item) => item.status !== "expired").map((item) => <article key={item.id} className="rounded-lg border bg-white p-4"><div className="mb-2 flex items-center justify-between"><span className={`rounded-full px-2 py-1 text-xs font-bold ${item.priority === "high" ? "bg-red-100 text-red-700" : item.priority === "medium" ? "bg-amber-100 text-amber-700" : "bg-slate-100 text-slate-600"}`}>{item.priority} · {item.kind}</span><span className="text-xs text-slate-400">Confianza {Math.round(item.confidence * 100)}%</span></div><h3 className="font-bold">{item.title}</h3><p className="mt-1 text-sm text-slate-600">{item.rationale}</p><div className="mt-3 rounded bg-indigo-50 p-2 text-sm"><b>Acción:</b> {item.proposedAction?.description}</div>{item.expectedImpact?.description && <div className="mt-2 text-xs text-slate-500">Impacto esperado: {item.expectedImpact.description}</div>}<div className="mt-3 flex gap-2">{item.status === "pending" ? <><button onClick={() => void decide(item.id, "approved")} disabled={busy} className="inline-flex items-center gap-1 rounded bg-emerald-600 px-3 py-1.5 text-xs font-semibold text-white"><Check className="h-3.5 w-3.5" /> Aprobar propuesta</button><button onClick={() => void decide(item.id, "rejected")} disabled={busy} className="inline-flex items-center gap-1 rounded border px-3 py-1.5 text-xs font-semibold"><X className="h-3.5 w-3.5" /> Descartar</button></> : <span className="text-xs font-semibold uppercase text-slate-500">{item.status === "approved" ? "Aprobada · pendiente de ejecución segura" : "Descartada"}</span>}</div></article>)}</div>{!items.length && <div className="rounded-lg border border-dashed bg-white p-6 text-center text-sm text-slate-500">Genera el primer plan cuando hayas registrado datos comerciales.</div>}</section>;
}
